FROM node:latest

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production
ENV FIREBASE_PROJECT_ID=
ENV FIREBASE_CLIENT_EMAIL=
ENV FIREBASE_PRIVATE_KEY=
ENV NEXT_PUBLIC_FIREBASE_API_KEY=
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
ENV NEXT_PUBLIC_FIREBASE_APP_ID=
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=
ENV GEMINI_API_KEY=
ENV HUGGINGFACE_API_KEY=

CMD ["npm", "start"]
